org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.incremental=false
android.builtInKotlin=true
android.newDsl=false
adMobAppId=ca-app-pub-8105551932366170~3399993415
