// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjixyscwTa1eprWJqN8D0XINGn4ogBYig',
    appId: '1:973039141229:web:9bd2554d0e96baf0da9a64',
    messagingSenderId: '973039141229',
    projectId: 'duck-downloader',
    authDomain: 'duck-downloader.firebaseapp.com',
    storageBucket: 'duck-downloader.firebasestorage.app',
    measurementId: 'G-EQSPJLHQ36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfwfF7_DazzH7tht7JwP37MymJeOiYrY',
    appId: '1:973039141229:android:f4937deab2877484da9a64',
    messagingSenderId: '973039141229',
    projectId: 'duck-downloader',
    storageBucket: 'duck-downloader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Bnputst4iNXVoTrm4OnC8k7WHO0m8R8',
    appId: '1:973039141229:ios:35840abb9c89bc21da9a64',
    messagingSenderId: '973039141229',
    projectId: 'duck-downloader',
    storageBucket: 'duck-downloader.firebasestorage.app',
    iosBundleId: 'com.example.duckDownloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Bnputst4iNXVoTrm4OnC8k7WHO0m8R8',
    appId: '1:973039141229:ios:35840abb9c89bc21da9a64',
    messagingSenderId: '973039141229',
    projectId: 'duck-downloader',
    storageBucket: 'duck-downloader.firebasestorage.app',
    iosBundleId: 'com.example.duckDownloader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjixyscwTa1eprWJqN8D0XINGn4ogBYig',
    appId: '1:973039141229:web:b2cbbbadcd7dd598da9a64',
    messagingSenderId: '973039141229',
    projectId: 'duck-downloader',
    authDomain: 'duck-downloader.firebaseapp.com',
    storageBucket: 'duck-downloader.firebasestorage.app',
    measurementId: 'G-1FHK7PENBB',
  );
}
