import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import '../../services/crash_reporting_service.dart';

typedef NotificationTapHandler = void Function(String? payload);

class NotificationService {
  NotificationService();

  late final Future<void> _initialized = _tryInitialize();
  NotificationTapHandler? _onTap;

  static final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();

  // Channel IDs.
  //
  // The suffix exists because a channel's sound is frozen at creation:
  // Android deliberately ignores any later attempt to change it, so shipping a
  // different sound means shipping a new channel id. That is the supported
  // way to do it — but the ids it replaces do not go away on their own.
  // Android keeps every channel an app has ever created until the app is
  // uninstalled, so three generations of these left users from the closed test
  // looking at nine entries under Settings → Notifications, six of them dead.
  // _staleChannelIds below is what stops that pile growing.
  static const _successChannelId = 'duck_downloads_success_v7';
  static const _failChannelId = 'duck_downloads_fail_v7';
  static const _clipboardChannelId = 'duck_clipboard_v7';

  /// Channel ids this app used to create and no longer does.
  ///
  /// Deleted on every start, which is safe to repeat: deleting a channel that
  /// was never created is a no-op. Anything added to the list above must be
  /// added here when it is superseded, or the clutter comes straight back.
  static const _staleChannelIds = <String>[
    'duck_downloads_success_v2',
    'duck_downloads_fail_v2',
    'duck_clipboard_v2',
    'duck_downloads_success_v4',
    'duck_downloads_fail_v4',
    'duck_clipboard_v4',
    // v6 held the old pairing, where the five-second sound was on the
    // clipboard hint — the app's most frequent and least important event —
    // and the short one on a failed download. The files swapped, and since a
    // channel's sound cannot be changed after creation, only a new id makes
    // that reach a device that already ran an older build.
    'duck_downloads_success_v6',
    'duck_downloads_fail_v6',
    'duck_clipboard_v6',
  ];

  Future<void> _tryInitialize() async {
    if (kIsWeb) return;
    try {
      // Must be a white-on-transparent silhouette: Android strips the colour
      // from notification small icons and keeps only the alpha, so pointing
      // this at the full-colour launcher icon rendered a solid white blob in
      // the status bar. Generated by tool/generate_icons.py.
      const androidSettings =
          AndroidInitializationSettings('@drawable/ic_notification');
      const iosSettings = DarwinInitializationSettings(
        requestAlertPermission: true,
        requestBadgePermission: true,
        requestSoundPermission: true,
        defaultPresentAlert: true,
        defaultPresentBadge: true,
        defaultPresentSound: true,
      );
      const settings = InitializationSettings(
        android: androidSettings,
        iOS: iosSettings,
      );
      await _plugin.initialize(
        settings,
        onDidReceiveNotificationResponse: (response) {
          _onTap?.call(response.payload);
        },
      );

      // ── Android 8+ requires explicit channel creation with sound ──────────
      // From API 26 the sound belongs to the channel and the one passed with
      // an individual notification is ignored outright, so the channel has to
      // exist — with the right sound — before the first notification is shown.
      //
      // The per-notification `sound:` further down is therefore not redundant
      // and must not be "cleaned up": minSdk is 24, and on Android 7 there are
      // no channels at all, so that argument is the only thing those devices
      // read.
      if (!kIsWeb && Platform.isAndroid) {
        await _createAndroidChannels();
      }
    } catch (error, stackTrace) {
      reportError(error, stackTrace, reason: 'notification-init');
    }
  }

  Future<void> _createAndroidChannels() async {
    final android = _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>();
    if (android == null) return;

    // Sweep the superseded ids before creating the current ones, so a user
    // upgrading from an older build ends up with three entries rather than
    // three more on top of what they already had.
    for (final id in _staleChannelIds) {
      try {
        await android.deleteNotificationChannel(id);
      } catch (error) {
        debugPrint('Could not remove stale channel $id: $error');
      }
    }

    await android.createNotificationChannel(
      const AndroidNotificationChannel(
        _successChannelId,
        'Duck Downloads',
        description: 'Download completed notifications',
        importance: Importance.max,
        playSound: true,
        sound: RawResourceAndroidNotificationSound('quack_success'),
        enableVibration: true,
      ),
    );

    await android.createNotificationChannel(
      const AndroidNotificationChannel(
        _failChannelId,
        'Duck Download Errors',
        description: 'Download failure notifications',
        importance: Importance.max,
        playSound: true,
        sound: RawResourceAndroidNotificationSound('quack_fail'),
        enableVibration: true,
      ),
    );

    await android.createNotificationChannel(
      const AndroidNotificationChannel(
        _clipboardChannelId,
        'Duck Clipboard',
        description: 'Clipboard link detected notifications',
        importance: Importance.high,
        playSound: true,
        sound: RawResourceAndroidNotificationSound('quack_clipboard'),
        enableVibration: false,
      ),
    );
  }

  Future<void> initialize({NotificationTapHandler? onTap}) async {
    _onTap = onTap;
    await _initialized;
  }

  Future<void> showDownloadComplete({
    required int id,
    required String title,
    required String type,
    String? downloadId,
  }) async {
    await _initialized;
    try {
      const androidDetails = AndroidNotificationDetails(
        _successChannelId,
        'Duck Downloads',
        channelDescription: 'Download completed notifications',
        importance: Importance.max,
        priority: Priority.high,
        playSound: true,
        enableVibration: true,
        sound: RawResourceAndroidNotificationSound('quack_success'),
      );
      const details = NotificationDetails(
        android: androidDetails,
        iOS: DarwinNotificationDetails(
          presentAlert: true,
          presentBadge: true,
          presentSound: true,
          sound: 'quack_success.mp3',
        ),
      );
      await _plugin.show(
        id,
        'Download Complete',
        '$type "$title" has been downloaded.',
        details,
        payload: downloadId,
      );
    } catch (error, stackTrace) {
      reportError(error, stackTrace, reason: 'notification-complete');
    }
  }

  Future<void> showDownloadFailed({
    required int id,
    required String title,
    required String error,
  }) async {
    await _initialized;
    try {
      const androidDetails = AndroidNotificationDetails(
        _failChannelId,
        'Duck Download Errors',
        channelDescription: 'Download failure notifications',
        importance: Importance.max,
        priority: Priority.high,
        playSound: true,
        enableVibration: true,
        sound: RawResourceAndroidNotificationSound('quack_fail'),
      );
      const details = NotificationDetails(
        android: androidDetails,
        iOS: DarwinNotificationDetails(
          presentAlert: true,
          presentBadge: true,
          presentSound: true,
          sound: 'quack_fail.mp3',
        ),
      );
      await _plugin.show(
        id,
        'Download Failed',
        '"$title" — $error',
        details,
      );
    } catch (error, stackTrace) {
      reportError(error, stackTrace, reason: 'notification-failed');
    }
  }

  Future<void> showClipboardDetected({
    required int id,
    required String url,
  }) async {
    await _initialized;
    try {
      const androidDetails = AndroidNotificationDetails(
        _clipboardChannelId,
        'Duck Clipboard',
        channelDescription: 'Clipboard link detected notifications',
        importance: Importance.high,
        priority: Priority.high,
        playSound: true,
        enableVibration: false,
        sound: RawResourceAndroidNotificationSound('quack_clipboard'),
      );
      const details = NotificationDetails(
        android: androidDetails,
        iOS: DarwinNotificationDetails(
          presentAlert: true,
          presentBadge: false,
          presentSound: true,
          sound: 'quack_clipboard.mp3',
        ),
      );
      await _plugin.show(
        id,
        'Link Detected',
        'Tap Duck Downloader to download this link.',
        details,
      );
    } catch (error, stackTrace) {
      reportError(error, stackTrace, reason: 'notification-clipboard');
    }
  }
}
